### ISSUE TITLE
Fiery Soul troll combo

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#155] opened 2016-01-26 02:58 UTC
Fiery soul with spammable toggles are banned. Why isn't sticky napalm, phase shift, quill spray banned then?
Spammable spells like nasal goo are fine, because it requires you to build it up mid-fight.

Spells that allow you to have it on 24/7 easily; are troll builds no doubt. 
I've never seen a game where fiery soul doesn't win you the game.

**Comment by ash47** [comment] 2016-01-30 00:35
@Jexah thoughts?

**Comment by Veroalla** [comment] 2016-01-30 02:47
Ask yourself, why are toggle spells considered troll with fiery soul? It's only 3 stacks that completely refresh on next spell.
I mean come on, you basicly get max attack/move speed the whole game. 
Beats any blink users in travel time too. OP farming capabilities.

**Comment by Jexah** [comment] 2016-01-30 07:30
Veroalla, by contrast I've never seen a game where Fiery Soul actually contributed to winning. Are you playing the standard balanced ruleset?

Lina can have Fiery Soul up 100% of the time, is she OP?

Fiery Soul is a strong skill, and with these skills generally we used to write a rule which said "This skill cannot be used with skills that have a cooldown of less than n seconds." Since then, we've become a bit more relaxed with the strictness of that rule, primarily to reduce complication with banning by reducing the number of banned combos you need to keep in mind.

If I recall correctly, Fiery Soul used to be a two or three seconds CD ban.

Personally I haven't seen this be used more effectively than other strong builds which I don't consider OP, so it is difficult to make a judgement call.

All that being said, as mentioned above, I'd like to know the ruleset that you play where you think this is considered OP.

**Comment by KaupoKytaru** [comment] 2016-02-05 20:33
"Lina can have Fiery Soul up 100% of the time, is she OP?"

By using different abilities that cost a lot of mana.
Late game it would be ok but max all that at lvl 7 with 0 mana cost?

**Comment by ash47** [comment] 2016-02-05 20:37
@Jexah

**Comment by Veroalla** [comment] 2016-02-08 14:28
# Why Fiery Soul should be in OP spells list
* Please read image alt text for details.
* These are easily re-produceable examples of fiery soul draft in 5-6 slot games with couple of bans, but standard settings. 
* Snowballing is super easy, at start lvl 1 or 6

I didn't cherry pick these settings, I always won with fiery soul, unless enemy also had similar drafts.

1. ![Fiery Soul](https://cdn.pbrd.co/images/1oXR1vrk.png "Enemy Centaur randomed bear return (troll was off) and went trolling the map with burrow+duel with almost 300+ dmg, WHILST INFESTED. OP spells on")
2. ![Fiery Soul](https://cdn.pbrd.co/images/1oYbtBYj.png "5vs2 Game basicly, all pick, no bans")
3. ![Fiery Soul](https://cdn.pbrd.co/images/1oYpmI48.png "4vs3 with my team feeding, all pick, 5 bans, 6 slots 2 ulti.")
4. ![Fiery Soul](https://cdn.pbrd.co/images/1oYLr3wx.png "4vs4 enemy had impetus + overpower and eyes in the forest, start lvl 11")
5. ![Fiery Soul](https://cdn.pbrd.co/images/1oYUHnDn.png "Badly feeding teammates, look at the difference in gpm/xpm, no fast jungle, enemy ragequit anyway. Start lvl 1, 6/5/2 mode, start gold 0")
6. ![Fiery Soul](https://cdn.pbrd.co/images/1oZ9CFS4.png "3vs3. Typical boring game with insane kill ratio, no effort")

@Jexah ![alt text](https://cdn.pbrd.co/images/1p00JYfT.png "Jexah")

**Comment by Jexah** [comment] 2016-02-08 23:05
@Veroalla Thanks for providing screen-caps, but end result doesn't really mean anything. I rarely get worse scores than these with builds that I don't think are OP, and I'm beaten by builds that I don't think are OP (generally early-mid game support builds).

If you have a personal vendetta against Fiery Soul (which I always seem to beat somehow), then just ban it. 10 bans per person is the "standard" number of bans, and in those games it still rarely gets banned, because it is a very "one trick pony". If the opposing team has a support (which I admit is uncommon) or a flash farmer, Fiery Soul gets destroyed.

Also, you mentioned Fury Swipes. This ability is usually banned 100% of the time.

The main reason togglables are banned with Fiery Soul is because we took a blanket approach with ability-proc passives, banning combinations that seemed broken by design, based on the original hero designs. The reason Fiery Soul isn't banned with lower CD abilities is because Lina's abilities are low-CD themselves

Consider Earthshaker, Aftershock is broken by design when looking at lower cooldown abilities, but Earthshaker can get away with it because his abilities are not low CD.

Having said all that...

The screen-caps you've provided are useless, but that doesn't mean that providing them is useless. It gives me the information that you're willing to actually back up your claims, and so I can ask you to provide specific information.  You can only imagine how much complaining we get about stuff being OP when it's actually just a case of a bad player vs a good player. If you're confident that the players you are playing against are actually better than you, and you're beating them 100% because of your build, providing screen-caps of the in-game scoreboard (the one that shows all of the builds in the current game) will give me some idea of the builds you're up against, and whether the players you're beating are actually decent.

We are currently working on some stuff, but we will also look at stat-tracking to help with balance.

Thanks for your assistance.

**Comment by Veroalla** [comment] 2016-02-08 23:50
You're correct. Aftershock is sometimes equally as powerful as fiery soul.
Fiery Soul is not on the same level as OP as cloak and dagger.

Burrow however is, shouldn't it be an ultimate? It's driving me nuts

**Comment by Jexah** [comment] 2016-02-08 23:54
I don't think burrow is OP. I've never lost to it. Dust/sents are your best friend. Once you have a dust on them or some sents down, burrow becomes a wasted slot.

Personally I don't find it very useful or powerful, but having said that I'm happy to look into making it an ult, although since it never gets banned -- even as a regular skill -- I'd be afraid of it never getting picked if it was an ult.

**Comment by ash47** [comment] 2016-02-09 12:37
I hate that ability XD

**Comment by Veroalla** [comment] 2016-02-09 14:27
Riki invisibility used to be an ultimate. The difference with burrow is
that you are extremely hard to kill with high regen and spell usage whilst
invisible.
Should this be an OP spell too? Being semi-stationary means you can't use
rot/ion shell, etc
It beats treants tree invisibility by far imho.

But the main issue is whether it should be an OP spell or just turned into
an ulti.
I mean, if Ash hates it, it's got to be a pretty good reason :p

Too bad there are not many people debating this matter. I mean have you
seen burrow+duel? It's rage inducing in the right hands.
Den 9 feb. 2016 13:37 skrev "Ashley Schmid" <notifications@github.com>:

> I hate that ability XD

**Comment by Jexah** [comment] 2016-02-09 22:35
I wrote several paragraphs on the train and submitted as I went into a tunnel. RIP. I'm getting tired of being verbose, and I have some stuff I have to get done at work so I'll keep it short, perhaps I will elaborate later.

- You are underrating mobility and in-game information.
- Burrow -- as it stands -- will not become an OP skill, we will look into making it an ult.
- Ash hates everything.
- If you are using Rot and Ion Shell with Nature's Guise, you're doing it wrong. Nature's Guise is a very powerful spell in the hands of a stunner support, as well as many other builds.

**Comment by Veroalla** [comment] 2016-02-10 18:18
Ok, let's try again. Here is one example:
Start lvl 1, 5 slots 1 ulti. +250 gold
![Alt Text](https://cdn.pbrd.co/images/1shGNE9S.jpg "Fury swiping team omg")
Match results:
![Alt Text](https://cdn.pbrd.co/images/1shzpyFp.png)

Compare the power of both teams drafts.

**Comment by Jexah** [comment] 2016-02-10 19:49
Mm, bad example. You and Rubik have builds which are not in contention, and Magnus and Troll have magic immunity which will be fixed soon. The fact that Rubik scored the best on your team with a bad build, and the available skills combined with what the enemies chose tells me that they picked trash builds. 

I'd say Trolls build is the best, then Magnus, then Rubik and the rest arent worth commenting on. 

Hard to say for sure, but looks like there was post-pone camping here too. 

This was clearly not a fair match in terms of skill. I played against a Fiery Soul, but to be fair he picked bad skills to go with it. He has Chem Rage behind the Magic Missile tool tip. 

http://puu.sh/n2x0i/3b88a8c01b.jpg

**Comment by ash47** [comment] 2016-02-27 21:41
Maybe we can just put it into the banning list? @Jexah

**Comment by Jexah** [comment] 2016-02-27 21:45
What is the "banning list"? @ash47

**Comment by ash47** [comment] 2016-02-27 22:07
The "balanced bans" list, the list of abilities that in a match with default rules will be banned to make the game more friendly for pub players.

@jexah

**Comment by Jexah** [comment] 2016-02-27 22:14
I don't think it should be banned by default. I've not once had any issues with Fiery Soul in the past 12 months, and there is really no evidence that it is more powerful than any of the other reasonable builds.

Not sure why this is still being discussed, if you agree with what I've said above then don't ban it, if you don't agree then ban it. Neither of us should be spending so much time on something so trivial.

**Comment by ash47** [comment] 2016-02-28 00:11
Maybe just ban it with phase shift cause that doesn't need mana, then you
can just counter easier with mana burn

**Comment by ash47** [comment] 2016-03-09 09:09
This issue is being closed, ferry soul will be banned by default via the LoD banning list :)

**Closed by ash47** 2016-03-09 09:09 UTC
Labels: enhancement
