### ISSUE TITLE
Nightstalker ultimate is tied to the hero model, not the darkness ability. 

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#255] opened 2016-05-02 07:25 UTC
I think its kind of bullshit, that only the night stalker hero can get the upgraded ultimate for darkness.

**Comment by darklordabc** [comment] 2016-05-02 07:26
You dont get unobstructed vision like you are meant to, if you play any other hero.

**Comment by Jexah** [comment] 2016-05-02 07:31
Why do you think it's bad? It's a trade-off, which is good for balance. Having heroes that have their own unique benefits expands the viable hero pool.

See Jugg, Terrorblade, Alchemist, Centaur, Ogre Magi, Mirana, Windranger, Enchantress, Techies, Lina, Chaos Knight, Slark, Meepo, Oracle, Pugna, Phantom Lancer, Outworld Devourer, etc.

Basically you want to remove one hero from the viable hero pool. Why?

**Comment by darklordabc** [comment] 2016-05-02 07:38
I dont know if your trolling or not.

**Comment by darklordabc** [comment] 2016-05-02 07:47
Trolling or not, what you are suggesting is retarded.

**Comment by ash47** [comment] 2016-05-02 09:03
It's not really retarded. If you go down this route then you need to change
all the stats to be the same on all the heroes in order to even it out.

The point is that many many heroes have very unique things that only apply
to them, and it also represents a serious amount of work to modify, as it
stands, it took an entire weekend of tinkering to remove the int steal from
silencer and attach it to the skill.

I've invested a serious amount of time into night stalker already, the way
the vision works is that when Nightstalker is created, the skill creates an
invisible unit that flies above him, when you get the scepter it increases
its night vision to be the same as night stalkers.

I have no way to remove or spawn an equivalent unit for other heroes.

It's a similar story with alchemist, the fact that be can gift scepters is
just hard coded into the hero, I'd need to rewrite the entire GUI in order
to fix it so it's tied to chemical rage, an already op skill.

**Comment by darklordabc** [comment] 2016-05-02 09:13
I already presumed it was difficult to uncouple certain special abilities because of how long it took to fix Silencer. But in the very least, these quirks should be advertised. I've played LoD for a long time, and I'm still discovering new ones.

**Comment by Jexah** [comment] 2016-05-02 10:02
Maybe you should write a wiki. Ever since 2012 LoD has had these kinds of quirks, and each Dota patch, new ones come out. It keeps the game fresh and interesting.

If you think they should be advertised, don't you think a wiki is a good way to start?

**Comment by darklordabc** [comment] 2016-05-02 11:03
No, I think the tooltip is a good place to start. Only a tiny minority of players are going to bother checking a wiki.

**Comment by ash47** [comment] 2016-05-02 11:38
Duplicate of #257

**Closed by ash47** 2016-05-02 11:38 UTC
