### ISSUE TITLE
[Bug] Ice Blast not being released + tower range

### ISSUE THREAD

**Issue by arthusagain** [ash47/LegendsOfDota#113] opened 2015-06-28 01:42 UTC
Ice Blast (Ancient Apparition's ultimate) wont change to the "Release" skill upon launching, unless it was placed in the slot the player usualy has as ultimate.
Also, increasing your range makes towers unnable to hit you (at least with extra towers)

**Comment by ohos** [comment] 2015-06-28 17:14
also it's not possible to use Ice Blast on Spells multiplier, because ball start flying insanely fast

**Comment by ash47** [comment] 2015-06-28 21:20
XD will look into this eventuality

**Comment by chrislafeken** [comment] 2015-06-29 01:12
I've played with Ice blast on every hotkey except maybe Q, and haven't reproduced it not changing to release even on the msot recent patch. Usually I place it on my hotkey D sinceI use it in non teamfights so i dont have to have it as a reflex hotkey. Anything that might help reproduce the situation?

**Comment by arthusagain** [comment] 2015-07-02 20:11
my hotkeys are q,e,r,t,g,f (being f the ultimate).i dont realy remember how was the match, but i think we had 3 normal slots and 2 either slots, and i had rocket flare, eye in the forest, sun ray, ice blast and thunder god's wrath.

**Comment by ash47** [comment] 2016-01-25 23:17
This seems to be fixed now, I have been able to use Ice Blast in multiple games now.

**Closed by ash47** 2016-01-25 23:17 UTC
