### ISSUE TITLE
The host doesn't get to pick settings...

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#168] opened 2016-02-08 22:55 UTC
If someone created a LOD lobby and then leave. someone else becomes host, 
the settings picker will then be randomized :(

**Comment by Jexah** [comment] 2016-02-08 23:11
As far as I know, if the host leaves and joins again, one person has to lock the teams, and a different person picks the LoD settings. I can't remember what the new or old hosts do, but one of them does one of the things, and the other does the other, haha. What you described -- as far as I know -- does not happen, but that does not mean that this isn't a bug. The expected behaviour is that when the host leaves and rejoins the lobby, they are no longer host or half-host or whatever is happening. This might be fixed in the next update.

@ash47 Mark as bug.

**Comment by Veroalla** [comment] 2016-02-08 23:26
Can you confirm having the host re-join makes him either the one to lock or do settings?
I can recall I hosted, but then re-joined, and I had no host power whatsoever... This was back in 2015 dec though

**Comment by Jexah** [comment] 2016-02-08 23:29
I can't confirm that, but I can confirm that there is an issue where there person that changes settings can be different from the person who locks the teams, and that it's related to the host leaving and rejoining.

**Comment by Veroalla** [comment] 2016-02-08 23:35
This will probably be fixed with Ash's new LoD UI
I don't recall, i.e, IMBA mode's settings having these issues. I'll check later perhaps.

Because the new UI makes the team locker the settings picker, which is nice!

**Comment by Jexah** [comment] 2016-02-08 23:37
Yep. Same with the ability to see the other team's skills if you swap teams in the team picker. A lot of these bugs might just vanish, but for the record it should be marked as a bug.

**Comment by Veroalla** [comment] 2016-02-14 01:56
will the new ui fix the disconnects when you finish picking settings?
Everyone gets "timed out" basicly

**Comment by ash47** [comment] 2016-02-14 01:57
It should, but I'm not sure really

**Comment by Jexah** [comment] 2016-02-14 23:12
I think this is a CPU related issue. When my CPU was underclocked (8 virtual cores at 1.5Ghz) I was getting this issue. Once I removed the underclock and enabled turbo boost (2.5Ghz-3.5Ghz) the issue no longer affected me. Perhaps we're loading too much stuff too fast, and the threads are getting locked up preventing the networking thread/s from getting any love. It could also be that the networking threads are getting killed due to too much load on the CPU, but I'm sceptical.

Honestly not sure why it is happening, but all I can say is that I DC'd every single time at 1.5Ghz, but after boosting the clock speed, I have not had this issue a single time. 

When everybody accepts and the loading starts, there are cases where the client crashes entirely. I think that is a RAM issue, since Dota doesn't clean up custom game modes or the main game mode once you disconnect from the server. It acts this way to increase subsequent load speeds, but if you only play a single rounds of multiple custom games in a single sitting, this is pointless. Not sure if there is anything that can be done about this at all, though. All I can say is that retiring Scaleform might help, which is happening in the new update.

**Comment by Veroalla** [comment] 2016-02-15 01:05
First we have to identify what this game does differently than other games. 
Maybe closing down the spell picking interface times you out?
Or maybe it has something to do with the timer getting paused?

**Comment by Jexah** [comment] 2016-02-15 01:16
The issue isn't so cut-and-dry. The first case you've stated implies a misunderstanding of the real issue. It may in fact be that the cause is "closing down the spell picking window", but please understand that nothing explicitly "times you out", since the issue was completely resolved for me once I boosted my CPU. The timing out is simply a symptom of the real issue, which we have yet to discover, let alone the cause.

The best course of action would be to wait and see if the new version fixes it, and if not, work back from the symptoms, rather than shooting in the dark. We've already established that the user being disconnected has something to do with the CPU, rather than the gamemode itself explicitly forcing the user to disconnect. This is backed up by the fact that only about half (give or take a couple) of the players are dropped at the time, rather than what you seem to believe which is that all of the players are dropped.

**Comment by ash47** [comment] 2016-02-27 10:51
This has either been fixed in the new GUI, or it won't be fixed -- who ever valves decides is the host will get hosting privileges.

**Closed by ash47** 2016-02-27 10:51 UTC
