### ISSUE TITLE
welcome page doesn't loads in half the games for half the people

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#70] opened 2015-06-19 17:20 UTC
welcome page doesn't loads in half the games for half the people

this mode really cool (i really want replace ugly valve's AD with this), i found it only after dota reborn open beta and seems this mode have serious issue, when all people connect, on hero selection screen should appear "welcome" window, but in half games it doesn't

in very rare cases not hosting player able to restart dota and reconnetc, then "welcome" window may appear, but may not

p.s. i can help debug if you explain how manually install, modify and compile this mode, at first i guess have to add debug messages to see what code pieces executed when all fine and what not executed when "welcome" window doesn't appear to find exact place where execution stop

**Comment by ash47** [comment] 2015-06-19 17:22
I'm clearly sleeping gosh, wait until I wake up lol

**Comment by ohos** [comment] 2015-06-19 17:24
it's okay, i'm from Moscrow, so my local time yet only 20:23 PM ^^

**Comment by ohos** [comment] 2015-06-19 18:36
i also can add to this bug, that even in case you can't see what host pick, you'll randomly ban skills and get random pick, but still able to play, seems missing "welcome" window only prevent picks

**Comment by ash47** [comment] 2015-06-19 22:11
Interesting, see, trouble is, I can't reproduce this, I'll do my best to solve the issues though :)

**Comment by Veroalla** [comment] 2015-06-19 22:36
He means that the "please wait while we waste your time" window and any LOD
UI doesn't appear.
This was a huge issue few days ago, did you fix it yet?

Temporary fix;, you had to restart Dota and reconnect. (simply reconnecting
without restarting didn't fix it)

**Comment by ash47** [comment] 2015-06-19 23:14
I have POSSIBLY fixed it, the issue is, I can't reproduce this -- I think I know the cause, I think I patched it, but I can't say for sure.

**Comment by ohos** [comment] 2015-06-20 13:10
did you released to public version with fix?

**Comment by ash47** [comment] 2015-06-23 11:30
Is this still relevant?

**Comment by Veroalla** [comment] 2015-06-23 12:08
No, everything is working  now. You can close this issue imho

**Closed** 2015-06-23 12:09 UTC
Labels: help wanted, question
